version: '3.8'

services:
  # Our FastAPI application service
  api:
    build: . # Build the image from the Dockerfile in the current directory
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace:cached # Mount our code into the container for live-reloading
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/legaldb
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - db # Don't start the api until the db is ready

  # Our PostgreSQL database service
  db:
    image: postgres:15 # Use the official PostgreSQL 15 image
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # Persist data even if the container stops
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=legaldb
    ports:
      - "5432:5432" # Expose the DB port to our host machine for easy access

volumes:
  postgres_data: # Define the named volume for data persistence